### ISSUE TITLE
Missing prerequisites on deployment guide

### ISSUE THREAD

**Issue by andres-lindo** [aws-solutions/simple-file-manager-for-amazon-efs#162] opened 2021-10-21 14:08 UTC
**Describe the bug**
Tried to deploy the solution with no error on the CloudFormation stack, however when using the solution the following error appears on Lambda execution logs, being unable to create the file system endpoint.

api - ERROR - An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id efs-manager-ManagedResources-fs-1a862b98 does not exist

I followed this guide: https://docs.aws.amazon.com/solutions/latest/simple-file-manager-for-amazon-efs

**To Reproduce**
-Launch the stack
-Reset auto-generated password
-Create a file manager Lambda function (never creates file manager)

**Expected behavior**
The File System ID link previously labeled false now returns true and the file system ID is now an active link. 

**Please complete the following information about the solution:**
- 1.4.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "simple-file-manager-for-amazon-efs/v1.0.4"
```

- [eu-west-1 ] Region: [e.g. us-east-1]
- [ No] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [Yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [Yes] Were there any errors in the CloudWatch Logs?
- api - ERROR - An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id efs-manager-ManagedResources-fs-1a862b98 does not exist

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by dreamorosi** [comment] 2021-11-18 17:54
The root cause was the fact that the EFS file system didn't have a mount target which in turns means it didn't have indication of subnetId nor security groupId which are [both required parameters](https://github.com/aws-solutions/simple-file-manager-for-amazon-efs/blob/development/source/api/chalicelib/file-manager-ap-lambda.template#L25-L28) for the creation of the proxy stack.

Andres is a colleague of mine and in this case he was just testing out the solution. The guide assumes that Customers already have an EFS file system deployed and all mount targets + Security Groups are in place. It'd be great to clarify this point in the guide.

**Comment by simonkrol** [comment] 2023-06-23 13:42
This documentation change appears to have made it into the limitations section of the [Implementation Guide](https://docs.aws.amazon.com/solutions/latest/simple-file-manager-for-amazon-efs/design-considerations.html). Closing.

**Closed by simonkrol** 2023-06-23 13:42 UTC
Labels: bug
